tavern_game/game/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('rations/', views.rations, name='rations'),
    path('add_rations/', views.add_rations, name='add_rations'),
    path('bar_purchases/', views.bar_purchases, name='bar_purchases'),
    path('add_bar_purchase/', views.add_bar_purchase, name='add_bar_purchase'),
    path('rich_people/', views.rich_people, name='rich_people'),
    path('rich_fortune/', views.rich_fortune, name='rich_fortune'),
    path('login/', LoginView.as_view(template_name='game/login.html', redirect_field_name='index'), name='login'),
    path('logout/', views.user_logout, name='logout'),
]

tavern_game/tavern_game/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('game/', include('game.urls')),
    path('admin/', admin.site.urls),
]

tavern_game/game/models.py
from django.db import models


class Person(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class Ration(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    value = models.IntegerField()

    def __str__(self):
        return '(Ration-%s-%s-%s)' % (self.timestamp, self.person, self.value)

    def __unicode__(self):
        return '(Ration-%s-%s-%s)' % (self.timestamp, self.person, self.value)


class BarPurchase(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    value = models.IntegerField()

    def __str__(self):
        return '(BarPurchase-%s-%s-%s)' % (self.timestamp, self.person, self.value)

    def __unicode__(self):
        return '(BarPurchase-%s-%s-%s)' % (self.timestamp, self.person, self.value)


class RichPerson(models.Model):
    person = models.OneToOneField(Person, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)
    value = models.IntegerField()

    def __str__(self):
        return '(RichPerson-%s-%s-%s)' % (self.timestamp, self.person, self.value)

    def __unicode__(self):
        return '(RichPerson-%s-%s-%s)' % (self.timestamp, self.person, self.value)

tavern_game/game/forms.py
from django import forms
from django.db.models import Q

from game.models import Person, Ration, BarPurchase, RichPerson


class AddRationsForm(forms.Form):
    person = forms.ModelMultipleChoiceField(
            queryset=Person.objects.all(),
            widget=forms.SelectMultiple(),
    )
    value = forms.IntegerField(min_value=1)


class AddBarPurchaseForm(forms.Form):
    person = forms.ModelChoiceField(
            queryset=Person.objects.all(),
            widget=forms.Select(),
            empty_label=None,
    )
    value = forms.IntegerField(min_value=1)


class RichPersonForm(forms.Form):
    person = forms.ModelChoiceField(
            queryset=Person.objects.all(),
            widget=forms.Select(),
            empty_label=None,
    )
    value = forms.IntegerField(min_value=1)

tavern_game/game/views.py
import datetime

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.db.models import Count, Sum

from .models import Ration, BarPurchase, RichPerson
from .forms import AddRationsForm, AddBarPurchaseForm, RichPersonForm

def index(request):
    return render(request, 'game/index.html', {})

def rations(request):
    ration_people = Ration.objects.values('person', 'person__name').annotate(sum=Sum('value')).order_by('-sum')

    last_sum = -1
    last_order = 0
    for ration in ration_people:
        if ration['sum'] != last_sum:
            last_order += 1
            last_sum = ration['sum']
            ration['rank'] = last_order

    context_dict = {
        'ration_people': ration_people,
    }
    return render(request, 'game/rations.html', context_dict)

@login_required
@staff_member_required
def add_rations(request):
    if request.method == 'POST':
        form = AddRationsForm(request.POST)
        if form.is_valid():
            person = form.cleaned_data.get('person')
            value = form.cleaned_data.get('value')

            request.session['last_value'] = value

            for p in person:
                rich = Ration.objects.create(
                        person=p,
                        value=value)

            return redirect('add_rations')
    else:
        if request.session.get('last_value', 0):
            form = AddRationsForm(initial={'value': request.session.get('last_value')})
        else:
            form = AddRationsForm()
    context_dict = {
        'form': form,
    }
    return render(request, 'game/add_rations.html', context_dict)

def bar_purchases(request):
    bar_people = BarPurchase.objects.values('person', 'person__name').annotate(sum=Sum('value')).order_by('-sum')

    last_sum = -1
    last_order = 0
    for bar in bar_people:
        if bar['sum'] != last_sum:
            last_order += 1
            last_sum = bar['sum']
            bar['rank'] = last_order

    context_dict = {
        'bar_people': bar_people,
    }
    return render(request, 'game/bar_purchases.html', context_dict)

@login_required
@staff_member_required
def add_bar_purchase(request):
    if request.method == 'POST':
        form = AddBarPurchaseForm(request.POST)
        if form.is_valid():
            person = form.cleaned_data.get('person')
            value = form.cleaned_data.get('value')

            rich = BarPurchase.objects.create(
                    person=person,
                    value=value)

            return redirect('add_bar_purchase')
    else:
        form = AddBarPurchaseForm()
    context_dict = {
        'form': form,
    }
    return render(request, 'game/add_bar_purchase.html', context_dict)

def rich_people(request):
    rich_people = RichPerson.objects.order_by('-value')

    last_value = -1
    last_order = 0
    for rich in rich_people:
        if rich.value != last_value:
            last_order += 1
            last_value = rich.value
            rich.rank = last_order

    context_dict = {
        'rich_people': rich_people,
    }
    return render(request, 'game/rich_people.html', context_dict)

@login_required
@staff_member_required
def rich_fortune(request):
    if request.method == 'POST':
        form = RichPersonForm(request.POST)
        if form.is_valid():
            person = form.cleaned_data.get('person')
            value = form.cleaned_data.get('value')

            rich = RichPerson.objects.filter(person=person).first()
            if rich is None:
                rich = RichPerson.objects.create(
                        person=person,
                        value=value)
            else:
                rich.value = value
                rich.save()

            return redirect('rich_fortune')
    else:
        form = RichPersonForm()
    context_dict = {
        'form': form,
    }
    return render(request, 'game/rich_fortune.html', context_dict)

@login_required
def user_logout(request):
    logout(request)
    return redirect('index')

tavern_game/game/templates/game/add_bar_purchase.html
{% extends 'game/main.html' %}
{% load widget_tweaks %}

{% block title %}Pridaj barový účet{% endblock %}

{% block style %}
    {{ block.super }}
    #id_person {
        overflow: hidden;
    }
    #add-bar-purchase-btn {
        width: 100%;
    }
{% endblock %}

{% block content %}
<h1>Pridaj barový účet</h1>

{% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{ form.non_field_errors }}
    </div>
{% endif %}

<form id="add_rations_form" method="post" action="/game/add_bar_purchase/">
    {% csrf_token %}
    <div class="row">
        <div class="col col-md-6">
            <div class="form-group">
                <label for="id_person">Ľudia</label>
                <select class="form-control" id="id_person" name="person" size={{ form.person | length }}>
                    {% for person in form.person %}
                        <option
                            value="{{ person.data.value }}"
                            {% if person.data.attrs.selected %}selected{% endif %}
                        >{{ person.data.label }}</option>
                    {% endfor %}
                <select>
            </div>
            {% if form.person.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ form.person.errors }}
                </div>
            {% endif %}
        </div>
        <div class="col col-md-6">
            <div class="form-group">
                <label for="id_value">Účet</label>
                {{ form.value | add_class:"form-control" }}
            </div>
            {% if form.value.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ form.value.errors }}
                </div>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col col-md-12">
            <button type="submit" class="btn btn-success btn-lg" id="add-bar-purchase-btn">Pridaj</button>
        </div>
    </div>
</form>
{% endblock %}

tavern_game/game/templates/game/add_rations.html
{% extends 'game/main.html' %}
{% load widget_tweaks %}

{% block title %}Pridaj dávku{% endblock %}

{% block style %}
    {{ block.super }}
    #id_person {
        overflow: hidden;
    }
    #add-ration-btn {
        width: 100%;
    }
{% endblock %}

{% block content %}
<h1>Pridaj dávku</h1>

{% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{ form.non_field_errors }}
    </div>
{% endif %}

<form id="add_rations_form" method="post" action="/game/add_rations/">
    {% csrf_token %}
    <div class="row">
        <div class="col col-md-6">
            <div class="form-group">
                <label for="id_person">Ľudia</label>
                <select class="form-control" id="id_person" name="person" multiple="multiple" size={{ form.person | length }}>
                    {% for person in form.person %}
                        <option
                            value="{{ person.data.value }}"
                            {% if person.data.attrs.selected %}selected{% endif %}
                        >{{ person.data.label }}</option>
                    {% endfor %}
                <select>
            </div>
            {% if form.person.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ form.person.errors }}
                </div>
            {% endif %}
        </div>
        <div class="col col-md-6">
            <div class="form-group">
                <label for="id_value">Hodnota dávky</label>
                {{ form.value | add_class:"form-control" }}
            </div>
            {% if form.value.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ form.value.errors }}
                </div>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col col-md-12">
            <button type="submit" class="btn btn-success btn-lg" id="add-ration-btn">Pridaj dávku</button>
        </div>
    </div>
</form>
{% endblock %}

tavern_game/game/templates/game/bar_purchases.html
{% extends 'game/main.html' %}

{% block title %}Barové účty{% endblock %}
{% block head %}
<meta http-equiv="refresh" content="30">
{% endblock %}

{% block content %}
    {% if error is not None %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
    {% else %}
        <h3>Barové účty</h3>
        <table class="table table-condensed table-bordered">
            <thead>
                <th>#</th>
                <th>Meno</th>
                <th class="text-center">Účet</th>
            </thead>
            <tbody>
                {% for bar_person in bar_people %}
                    <tr>
                        <td>{{ bar_person.rank }}</td>
                        <td>{{ bar_person.person__name }}</td>
                        <td class="text-center"><b>{{ bar_person.sum }}</b></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}

tavern_game/game/templates/game/index.html
{% extends 'game/main.html' %}

{% block title %}TavernGame{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <h1>TavernGame says... hello {{ user.username }}!</h1>
    {% else %}
        <h1>Hello UfoPrask!</h1>
        <a href="{% url 'login' %}" class="btn btn-primary">Login</a>
    {% endif %}
{% endblock %}

tavern_game/game/templates/game/login.html
{% extends 'game/main.html' %}
{% load widget_tweaks %}

{% block title %}Login{% endblock %}

{% block content %}
<h1>Login to TavernGame</h1>

{% if form.errors %}
    <div class="alert alert-danger" role="alert">
        <p>Your username and password didn't match. Please try again.</p>
    </div>
{% endif %}
<form id="login_form" method="post" action="{% url 'login' %}">
    {% csrf_token %}
    <div class="form-group">
        {{ form.username.label_tag }}
        {% render_field form.username class+="form-control" %}
    </div>
    <div class="form-group">
        {{ form.password.label_tag }}
        {% render_field form.password class+="form-control" %}
    </div>

    <button type="submit" class="btn btn-primary">Login</button>
    </form>
</form>
{% endblock %}

tavern_game/game/templates/game/main.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

    <head>
        <link rel="stylesheet" href="{% static 'game/css/bootstrap.min.css' %}">
        <link rel="icon" type="image/png" href="{% static "game/favicon.ico" %}"/>
        <title>{% block title %}TavernGame{% endblock %}</title>
        <style>
            {% block style %}{% endblock %}
        </style>
        {% block head %}{% endblock %}
    </head>

    <body>
        <div class="container">
            {% include 'game/nav.html' %}
            {% block content %}
            {% endblock %}
        </div>


        {% block js %}
            <script src="{% static 'game/js/jquery-latest.min.js' %}" type="text/javascript"></script>
            <script src="{% static 'game/js/popper.min.js' %}" type="text/javascript"></script>
            <script src="{% static 'game/js/bootstrap.min.js' %}" type="text/javascript"></script>
        {% endblock js %}
    </body>

</html>

tavern_game/game/templates/game/nav.html
<nav class="navbar navbar-default static-top">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/game">TavernGame</a>
        </div>

<!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'rations' %}">Dávky</a></td>
                <li><a href="{% url 'bar_purchases' %}">Barové účty</a></td>
                <li><a href="{% url 'rich_people' %}">Najbohatší ľudia</a></td>
                {% if user.is_authenticated %}
                    {% if user.is_staff %}
                        <li><a href="{% url 'add_rations' %}">Pridaj dávku</a></td>
                        <li><a href="{% url 'add_bar_purchase' %}">Pridaj barový účet</a></td>
                        <li><a href="{% url 'rich_fortune' %}">Nastav bohatému stav</a></td>
                    {% endif %}
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }} <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'logout' %}">Logout</a></td>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}">Login</a></td>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

tavern_game/game/templates/game/rations.html
{% extends 'game/main.html' %}

{% block title %}Dávky{% endblock %}
{% block head %}
<meta http-equiv="refresh" content="30">
{% endblock %}

{% block content %}
    {% if error is not None %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
    {% else %}
        <h3>Dávky</h3>
        <table class="table table-condensed table-bordered">
            <thead>
                <th>#</th>
                <th>Meno</th>
                <th class="text-center">Dávky</th>
            </thead>
            <tbody>
                {% for ration_person in ration_people %}
                    <tr>
                        <td>{{ ration_person.rank }}</td>
                        <td>{{ ration_person.person__name }}</td>
                        <td class="text-center"><b>{{ ration_person.sum }}</b></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}

tavern_game/game/templates/game/rich_fortune.html
{% extends 'game/main.html' %}
{% load widget_tweaks %}

{% block title %}Nastav bohatému stav{% endblock %}

{% block style %}
    {{ block.super }}
    #id_person {
        overflow: hidden;
    }
    #rich-fortune-btn {
        width: 100%;
    }
{% endblock %}

{% block content %}
<h1>Nastav bohatému stav</h1>

{% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{ form.non_field_errors }}
    </div>
{% endif %}

<form id="rich_fortune_form" method="post" action="/game/rich_fortune/">
    {% csrf_token %}
    <div class="row">
        <div class="col col-md-6">
            <div class="form-group">
                <label for="id_person">Ľudia</label>
                <select class="form-control" id="id_person" name="person" size={{ form.person | length }}>
                    {% for person in form.person %}
                        <option
                            value="{{ person.data.value }}"
                            {% if person.data.attrs.selected %}selected{% endif %}
                        >{{ person.data.label }}</option>
                    {% endfor %}
                <select>
            </div>
            {% if form.person.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ form.person.errors }}
                </div>
            {% endif %}
        </div>
        <div class="col col-md-6">
            <div class="form-group">
                <label for="id_value">Stav</label>
                {{ form.value | add_class:"form-control" }}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col col-md-12">
            <button type="submit" class="btn btn-success btn-lg" id="rich-fortune-btn">Nastav</button>
        </div>
    </div>
</form>
{% endblock %}

tavern_game/game/templates/game/rich_people.html
{% extends 'game/main.html' %}

{% block title %}Najbohatší ľudia{% endblock %}
{% block head %}
<meta http-equiv="refresh" content="30">
{% endblock %}

{% block content %}
    {% if error is not None %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
    {% else %}
        <h3>Najbohatší ľudia</h3>
        <table class="table table-condensed table-bordered">
            <thead>
                <th>#</th>
                <th>Meno</th>
                <th class="text-center">Majetok</th>
            </thead>
            <tbody>
                {% for rich_person in rich_people %}
                    <tr>
                        <td>{{ rich_person.rank }}</td>
                        <td>{{ rich_person.person.name }}</td>
                        <td class="text-center"><b>{{ rich_person.value }}</b></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}